# Generated by Django 4.0 on 2022-02-14 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_timestamp_writer_alter_article_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 0, 5, 41, 536358)),
        ),
    ]
