# Generated by Django 4.0 on 2022-02-14 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 0, 59, 20, 764041)),
        ),
    ]
