# Generated by Django 4.0 on 2022-02-23 15:14

import articles.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_options_alter_article_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.cover_uploader),
        ),
        migrations.AlterField(
            model_name='article',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 18, 44, 48, 492872)),
        ),
    ]
